project:
  type: website
  output-dir: docs

website:
  title: "Data Lab"
  site-url: https://sghizzus.github.io/Data-Lab/
  description: "Un blog per parlare del mondo attraverso i dati"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Sghizzus/
      - icon: rss
        href: index.xml
format:
  html:
    fig-width: 6
    fig-asp: 0.618
    theme: 
      - cerulean
      - brand
    css: styles.css

editor: visual

lang: it

execute:
  echo: false
  warning: false
  error: false
  message: false
  
knitr:
  opts_chunk: 
    out-width: "70%"
    fig-align: center
    fig_retina: 1
    fig.showtext: true
