project:
  type: website
  output-dir: docs

website:
  title: "Data Lab"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Sghizzus/ivanmarino
format:
  html:
    theme: 
      - cerulean
      - brand
    css: styles.css

editor: visual

