project:
  type: website
  output-dir: docs

website:
  title: "Data Lab"
  site-url: https://sghizzus.github.io/Data-Lab/
  description: "Un blog per parlare del mondo attraverso i dati"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Sghizzus/
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      - cerulean
      - brand
    css: styles.css

editor: visual

lang: it
